# put your configuration values here

[runtime]
log_level="WARNING"  # the system log level of dlt
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/reference/telemetry
dlthub_telemetry = true

[sources.rest_api]
resources = ["a", "b", "c"] # please set me up!
[sources.rest_api.client] # please set me up!
key = "value"

[destination.filesystem]
bucket_url = "s3://mybucket" 

[destination.filesystem.credentials]
aws_access_key_id = "minio"
aws_secret_access_key = "minio123" 
endpoint_url = "http://127.0.0.1:9000" 

[normalize]
loader_file_format="csv"

[normalize.data_writer]
disable_compression=true